name: githubcities

# development environment

services:

# Todo: clean up this and test in dev and update traefik-proxy prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: githubcities-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/apps/web/.env
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - default
      - proxy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: githubcities-backend
    restart: unless-stopped
    # don't mount alembic as volume
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - default
      - proxy

  database:
    image: postgres:17.5-alpine3.22
    container_name: githubcities-database
    restart: unless-stopped
    command: ["postgres", "-p", "5434"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # postgres user 999:999 must own the volume
    # ok in dev, python watch will complain
    # user: '${MY_UID}:${MY_GID}'
    # ports:
    #   - 5434:5434
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./backend/data/database:/var/lib/postgresql/data # !without /pgdata
    networks:
      - default

  adminer:
    image: adminer:5.4.0-standalone
    container_name: githubcities-adminer
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - ADMINER_DESIGN=nicu
    # change default port
    command: php -S 0.0.0.0:8083 -t /var/www/html
    #
    # must use database:5432, 5433:5432 mapping does not apply
    ports:
      - 8083:8083
    # no networks, no ports
    # network_mode: host
    networks:
      - default
      - proxy

networks:
  default:
    internal: true
  proxy:
    external: true