import { urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';

import type { Client, Options as Options2, TDataShape } from './client';
import type {
  ItemsCreateItemData,
  ItemsCreateItemErrors,
  ItemsCreateItemResponses,
  ItemsDeleteItemData,
  ItemsDeleteItemErrors,
  ItemsDeleteItemResponses,
  ItemsReadItemData,
  ItemsReadItemErrors,
  ItemsReadItemResponses,
  ItemsReadItemsData,
  ItemsReadItemsErrors,
  ItemsReadItemsResponses,
  ItemsUpdateItemData,
  ItemsUpdateItemErrors,
  ItemsUpdateItemResponses,
  LoginAuthGithubCallbackData,
  LoginAuthGithubCallbackResponses,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenErrors,
  LoginLoginAccessTokenResponses,
  LoginLoginGithubData,
  LoginLoginGithubResponses,
  LoginLogoutData,
  LoginLogoutResponses,
  LoginRecoverPasswordData,
  LoginRecoverPasswordErrors,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentErrors,
  LoginRecoverPasswordHtmlContentResponses,
  LoginRecoverPasswordResponses,
  LoginResetPasswordData,
  LoginResetPasswordErrors,
  LoginResetPasswordResponses,
  LoginTestTokenData,
  LoginTestTokenResponses,
  PrivateCreateUserData,
  PrivateCreateUserErrors,
  PrivateCreateUserResponses,
  UsersCreateUserData,
  UsersCreateUserErrors,
  UsersCreateUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserMeData,
  UsersDeleteUserMeResponses,
  UsersDeleteUserResponses,
  UsersReadUserByIdData,
  UsersReadUserByIdErrors,
  UsersReadUserByIdResponses,
  UsersReadUserMeData,
  UsersReadUserMeResponses,
  UsersReadUsersData,
  UsersReadUsersErrors,
  UsersReadUsersResponses,
  UsersRegisterUserData,
  UsersRegisterUserErrors,
  UsersRegisterUserResponses,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeErrors,
  UsersUpdatePasswordMeResponses,
  UsersUpdateUserData,
  UsersUpdateUserErrors,
  UsersUpdateUserMeData,
  UsersUpdateUserMeErrors,
  UsersUpdateUserMeResponses,
  UsersUpdateUserResponses,
  UtilsHealthCheckData,
  UtilsHealthCheckResponses,
  UtilsTestEmailData,
  UtilsTestEmailErrors,
  UtilsTestEmailResponses,
} from './types.gen';

// This file is auto-generated by @hey-api/openapi-ts

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class LoginService {
  /**
   * Login Access Token
   *
   * OAuth2-compatible token login: get an access token for future requests (sent in an HTTP-only cookie)
   */
  public static loginAccessToken<ThrowOnError extends boolean = false>(
    options: Options<LoginLoginAccessTokenData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      LoginLoginAccessTokenResponses,
      LoginLoginAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      url: '/api/v1/login/access-token',
      ...options,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers,
      },
    });
  }

  /**
   * Test Token
   *
   * Test access token
   */
  public static testToken<ThrowOnError extends boolean = false>(
    options?: Options<LoginTestTokenData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<LoginTestTokenResponses, unknown, ThrowOnError>({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/login/test-token',
      ...options,
    });
  }

  /**
   * Recover Password
   *
   * Password Recovery
   */
  public static recoverPassword<ThrowOnError extends boolean = false>(
    options: Options<LoginRecoverPasswordData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      LoginRecoverPasswordResponses,
      LoginRecoverPasswordErrors,
      ThrowOnError
    >({ url: '/api/v1/password-recovery/{email}', ...options });
  }

  /**
   * Reset Password
   *
   * Reset password
   */
  public static resetPassword<ThrowOnError extends boolean = false>(
    options: Options<LoginResetPasswordData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      LoginResetPasswordResponses,
      LoginResetPasswordErrors,
      ThrowOnError
    >({
      url: '/api/v1/reset-password/',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Recover Password Html Content
   *
   * HTML Content for Password Recovery
   */
  public static recoverPasswordHtmlContent<ThrowOnError extends boolean = false>(
    options: Options<LoginRecoverPasswordHtmlContentData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      LoginRecoverPasswordHtmlContentResponses,
      LoginRecoverPasswordHtmlContentErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/password-recovery-html-content/{email}',
      ...options,
    });
  }

  /**
   * Logout
   *
   * Delete the HTTP-only cookie during logout
   */
  public static logout<ThrowOnError extends boolean = false>(
    options?: Options<LoginLogoutData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<LoginLogoutResponses, unknown, ThrowOnError>({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/logout',
      ...options,
    });
  }

  /**
   * Login Github
   *
   * Redirect to GitHub login page
   * Must initiate OAuth flow from backend
   */
  public static loginGithub<ThrowOnError extends boolean = false>(
    options?: Options<LoginLoginGithubData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<LoginLoginGithubResponses, unknown, ThrowOnError>({
      url: '/api/v1/login/github',
      ...options,
    });
  }

  /**
   * Auth Github Callback
   *
   * GitHub OAuth callback, GitHub will call this endpoint
   */
  public static authGithubCallback<ThrowOnError extends boolean = false>(
    options?: Options<LoginAuthGithubCallbackData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<LoginAuthGithubCallbackResponses, unknown, ThrowOnError>(
      { url: '/api/v1/auth/github/callback', ...options }
    );
  }
}

export class UsersService {
  /**
   * Read Users
   *
   * Retrieve users.
   */
  public static readUsers<ThrowOnError extends boolean = false>(
    options?: Options<UsersReadUsersData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      UsersReadUsersResponses,
      UsersReadUsersErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/',
      ...options,
    });
  }

  /**
   * Create User
   *
   * Create new user.
   */
  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<UsersCreateUserData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      UsersCreateUserResponses,
      UsersCreateUserErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Register User
   *
   * Create new user without the need to be logged in.
   */
  public static registerUser<ThrowOnError extends boolean = false>(
    options: Options<UsersRegisterUserData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      UsersRegisterUserResponses,
      UsersRegisterUserErrors,
      ThrowOnError
    >({
      url: '/api/v1/users/signup',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Delete User Me
   *
   * Delete own user.
   */
  public static deleteUserMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersDeleteUserMeData, ThrowOnError>
  ) {
    return (options?.client ?? client).delete<UsersDeleteUserMeResponses, unknown, ThrowOnError>({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/me',
      ...options,
    });
  }

  /**
   * Read User Me
   *
   * Get current user.
   */
  public static readUserMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersReadUserMeData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<UsersReadUserMeResponses, unknown, ThrowOnError>({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/me',
      ...options,
    });
  }

  /**
   * Update User Me
   *
   * Update own user.
   */
  public static updateUserMe<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateUserMeData, ThrowOnError>
  ) {
    return (options.client ?? client).patch<
      UsersUpdateUserMeResponses,
      UsersUpdateUserMeErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/me',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Update Password Me
   *
   * Update own password.
   */
  public static updatePasswordMe<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdatePasswordMeData, ThrowOnError>
  ) {
    return (options.client ?? client).patch<
      UsersUpdatePasswordMeResponses,
      UsersUpdatePasswordMeErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/me/password',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Delete User
   *
   * Delete a user.
   */
  public static deleteUser<ThrowOnError extends boolean = false>(
    options: Options<UsersDeleteUserData, ThrowOnError>
  ) {
    return (options.client ?? client).delete<
      UsersDeleteUserResponses,
      UsersDeleteUserErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/{user_id}',
      ...options,
    });
  }

  /**
   * Read User By Id
   *
   * Get a specific user by id.
   */
  public static readUserById<ThrowOnError extends boolean = false>(
    options: Options<UsersReadUserByIdData, ThrowOnError>
  ) {
    return (options.client ?? client).get<
      UsersReadUserByIdResponses,
      UsersReadUserByIdErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/{user_id}',
      ...options,
    });
  }

  /**
   * Update User
   *
   * Update a user.
   */
  public static updateUser<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateUserData, ThrowOnError>
  ) {
    return (options.client ?? client).patch<
      UsersUpdateUserResponses,
      UsersUpdateUserErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/users/{user_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class UtilsService {
  /**
   * Test Email
   *
   * Test emails.
   */
  public static testEmail<ThrowOnError extends boolean = false>(
    options: Options<UtilsTestEmailData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      UtilsTestEmailResponses,
      UtilsTestEmailErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/utils/test-email/',
      ...options,
    });
  }

  /**
   * Health Check
   */
  public static healthCheck<ThrowOnError extends boolean = false>(
    options?: Options<UtilsHealthCheckData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<UtilsHealthCheckResponses, unknown, ThrowOnError>({
      url: '/api/v1/utils/health-check/',
      ...options,
    });
  }
}

export class ItemsService {
  /**
   * Read Items
   *
   * Retrieve items.
   */
  public static readItems<ThrowOnError extends boolean = false>(
    options?: Options<ItemsReadItemsData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ItemsReadItemsResponses,
      ItemsReadItemsErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/items/',
      ...options,
    });
  }

  /**
   * Create Item
   *
   * Create new item.
   */
  public static createItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsCreateItemData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      ItemsCreateItemResponses,
      ItemsCreateItemErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/items/',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }

  /**
   * Delete Item
   *
   * Delete an item.
   */
  public static deleteItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsDeleteItemData, ThrowOnError>
  ) {
    return (options.client ?? client).delete<
      ItemsDeleteItemResponses,
      ItemsDeleteItemErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/items/{id}',
      ...options,
    });
  }

  /**
   * Read Item
   *
   * Get item by ID.
   */
  public static readItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsReadItemData, ThrowOnError>
  ) {
    return (options.client ?? client).get<
      ItemsReadItemResponses,
      ItemsReadItemErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/items/{id}',
      ...options,
    });
  }

  /**
   * Update Item
   *
   * Update an item.
   */
  public static updateItem<ThrowOnError extends boolean = false>(
    options: Options<ItemsUpdateItemData, ThrowOnError>
  ) {
    return (options.client ?? client).put<
      ItemsUpdateItemResponses,
      ItemsUpdateItemErrors,
      ThrowOnError
    >({
      security: [
        {
          in: 'cookie',
          name: 'auth_cookie',
          type: 'apiKey',
        },
      ],
      url: '/api/v1/items/{id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}

export class PrivateService {
  /**
   * Create User
   *
   * Create a new user.
   */
  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<PrivateCreateUserData, ThrowOnError>
  ) {
    return (options.client ?? client).post<
      PrivateCreateUserResponses,
      PrivateCreateUserErrors,
      ThrowOnError
    >({
      url: '/api/v1/private/users/',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });
  }
}
